"""add initial schemas

Revision ID: 0e1a3515b326
Revises: 
Create Date: 2025-12-29 16:02:12.386182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1a3515b326'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('invite_code', sa.Text(), nullable=False),
    sa.Column('accepting_members', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code'),
    sa.UniqueConstraint('team_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hackathon_submissions',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_url', sa.Text(), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('won_rank', sa.Integer(), nullable=True),
    sa.CheckConstraint('won_rank IS NULL OR (won_rank > 0 AND won_rank <= 3)', name='won_rank_check'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('won_rank')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_leader', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_index('team_members_user_id_unique', 'team_members', ['user_id'], unique=True)
    op.create_table('team_points',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'added_at')
    )
    op.create_index('team_points_team_id_idx', 'team_points', ['team_id'], unique=False)
    op.create_table('team_submit_attempts',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'problem_id', 'submitted_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_submit_attempts')
    op.drop_index('team_points_team_id_idx', table_name='team_points')
    op.drop_table('team_points')
    op.drop_index('team_members_user_id_unique', table_name='team_members')
    op.drop_table('team_members')
    op.drop_table('hackathon_submissions')
    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
