"""remove hackathon table

Revision ID: 2c26389e75ed
Revises: 0e1a3515b326
Create Date: 2025-12-29 16:47:02.542094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c26389e75ed'
down_revision: Union[str, Sequence[str], None] = '0e1a3515b326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hackathon_submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathon_submissions',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('project_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('won_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('won_rank IS NULL OR won_rank > 0 AND won_rank <= 3', name=op.f('won_rank_check')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('hackathon_submissions_team_id_fkey')),
    sa.PrimaryKeyConstraint('team_id', name=op.f('hackathon_submissions_pkey')),
    sa.UniqueConstraint('won_rank', name=op.f('hackathon_submissions_won_rank_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
