"""modify team FKs cascading deletions

Revision ID: 59184a2d0c70
Revises: c7824d0fa2cc
Create Date: 2026-02-24 15:54:17.387386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "59184a2d0c70"
down_revision: Union[str, Sequence[str], None] = "c7824d0fa2cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("team_members_team_id_fkey"), "team_members", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("team_members_user_id_fkey"), "team_members", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "team_members", "teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "team_members", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("team_points_team_id_fkey"), "team_points", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "team_points", "teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "team_submit_attempts",
        "submitted_by_user_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_constraint(
        op.f("team_submit_attempts_team_id_fkey"),
        "team_submit_attempts",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("team_submit_attempts_submitted_by_user_id_fkey"),
        "team_submit_attempts",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "team_submit_attempts", "teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "team_submit_attempts",
        "users",
        ["submitted_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "team_submit_attempts_team_id_fkey", "team_submit_attempts", type_="foreignkey"
    )
    op.drop_constraint(
        "team_submit_attempts_submitted_by_user_id_fkey",
        "team_submit_attempts",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("team_submit_attempts_submitted_by_user_id_fkey"),
        "team_submit_attempts",
        "users",
        ["submitted_by_user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("team_submit_attempts_team_id_fkey"),
        "team_submit_attempts",
        "teams",
        ["team_id"],
        ["id"],
    )
    op.alter_column(
        "team_submit_attempts",
        "submitted_by_user_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_constraint("team_points_team_id_fkey", "team_points", type_="foreignkey")
    op.create_foreign_key(
        op.f("team_points_team_id_fkey"), "team_points", "teams", ["team_id"], ["id"]
    )
    op.drop_constraint("team_members_team_id_fkey", "team_members", type_="foreignkey")
    op.drop_constraint("team_members_user_id_fkey", "team_members", type_="foreignkey")
    op.create_foreign_key(
        op.f("team_members_user_id_fkey"), "team_members", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("team_members_team_id_fkey"), "team_members", "teams", ["team_id"], ["id"]
    )
    # ### end Alembic commands ###
