/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SigninSsoCallbackIndexRouteImport } from './routes/signin/sso-callback/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninSsoCallbackIndexRoute = SigninSsoCallbackIndexRouteImport.update({
  id: '/signin/sso-callback/',
  path: '/signin/sso-callback/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin/sso-callback': typeof SigninSsoCallbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin/sso-callback': typeof SigninSsoCallbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin/sso-callback/': typeof SigninSsoCallbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin/sso-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin/sso-callback'
  id: '__root__' | '/' | '/signin/sso-callback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninSsoCallbackIndexRoute: typeof SigninSsoCallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/sso-callback/': {
      id: '/signin/sso-callback/'
      path: '/signin/sso-callback'
      fullPath: '/signin/sso-callback'
      preLoaderRoute: typeof SigninSsoCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninSsoCallbackIndexRoute: SigninSsoCallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
