/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SigninSsoCallbackIndexRouteImport } from './routes/signin/sso-callback/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninSsoCallbackIndexRoute = SigninSsoCallbackIndexRouteImport.update({
  id: '/signin/sso-callback/',
  path: '/signin/sso-callback/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/problems': typeof ProblemsRoute
  '/team': typeof TeamRoute
  '/signin/sso-callback': typeof SigninSsoCallbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/problems': typeof ProblemsRoute
  '/team': typeof TeamRoute
  '/signin/sso-callback': typeof SigninSsoCallbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/problems': typeof ProblemsRoute
  '/team': typeof TeamRoute
  '/signin/sso-callback/': typeof SigninSsoCallbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/problems'
    | '/team'
    | '/signin/sso-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leaderboard' | '/problems' | '/team' | '/signin/sso-callback'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/problems'
    | '/team'
    | '/signin/sso-callback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProblemsRoute: typeof ProblemsRoute
  TeamRoute: typeof TeamRoute
  SigninSsoCallbackIndexRoute: typeof SigninSsoCallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/sso-callback/': {
      id: '/signin/sso-callback/'
      path: '/signin/sso-callback'
      fullPath: '/signin/sso-callback'
      preLoaderRoute: typeof SigninSsoCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProblemsRoute: ProblemsRoute,
  TeamRoute: TeamRoute,
  SigninSsoCallbackIndexRoute: SigninSsoCallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
