name: Madness Dailies - Reminder

on:
  schedule:
    - cron: "0 20 16-20 3 *"
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    # Fix for the Node.js 20 deprecation warning
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          # Fix for the "Dependencies file not found" error
          cache-dependency-path: madness-dailies/go.sum

      - name: Create .env file from secrets
        working-directory: madness-dailies
        run: |
          echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> .env
          echo "ROLE_ID=${{ secrets.ROLE_ID }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env

      - name: Run Go Program
        working-directory: madness-dailies
        run: |
          go mod download
          go run . --reminder
